### ISSUE TITLE
load fixtures from a specific folder only

### ISSUE THREAD

**Issue by craue** [doctrine/DoctrineFixturesBundle#226] opened 2017-12-18 01:04 UTC
With 3.0, how is it possible to make the `doctrine:fixtures:load` command consider fixtures from a specific folder only, like the `--fixtures` option did? This feature is [still needed](https://github.com/craue/CraueGeoBundle/pull/16#issuecomment-352023730).

**Comment by alcaeus** [comment] 2017-12-18 06:27
Duplicate of #219. Closing to consolidate discussion.

**Closed by alcaeus** 2017-12-18 06:27 UTC
